language: node_js
node_js:
    - "6.1.0"
before_script:
    - npm install
env:
  - NODE_ENV=development
script:
    - npm run build
    - npm run test:coverage
    - npm run lint:all
notifications:
  slack: cejs-atsistemas:XxetFLj7MuJALpcVhx2PKEE6#react-base
    on_success: always
    on_failure: always
    on_start: never
    on_pull_requests: false
