language: node_js
node_js:
    - "6.1.0"
before_script:
    - npm install
script:
    - node_modules/eslint/bin/eslint.js app --ignore-pattern '*.spec.js'  --ext .js --ext .jsx
    - mocha \"./app/**/*.spec.js\" --compilers js:babel-core/register --recursive --require ignore-styles
